### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by MasterGeekMX** [lachhebo/GabTag#4]
Title says it. I will help on making the translation to spanish if that counts.

**Comment by lachhebo** [comment]
Thanks, 

You can write a es.po file on the po folder, i did not fully understand how translation work with meson but i'm sure this file is related to the translation.

**Comment by lachhebo** [comment]
I have done a bit of research and created a Transifex repository for the project. 

If you send me your email address, i can give a link to the Transifex repository of the project, you would have a translator role and you would be able to easily add translation in Spanish.

**Comment by MasterGeekMX** [comment]
Sorry for the late response. Use the same email that I'm using right now.

**Comment by lachhebo** [comment]
No big deal. 

I can't access your email within github. Send me an email to ismael.lachheb@protonmail.com and i will send you the link to Transifex repo.
